### ISSUE TITLE
web-education role

### ISSUE THREAD

**Issue by dgu123** [OPEN-ENT-NG/springboard-open-ent#4]
bonjour,

ou sont définit les roles dans  le framework ?? par example web-education role ??

merci ,
david

**Comment by elbywan** [comment]
Bonjour,

Je ne comprends pas vraiment la question. 
Pouvez-vous préciser ?

Si vous faites référence au rôle postgresql, comme répondu précédemment, c'est dans la configuration (`sqlUsername`).

**Comment by dgu123** [comment]
role "web-education" does not exist
je l ai pas vue dans la doc et ce n'est pas dans mes confs donc je me demande d ou cela vient??
de mon cote j ai :
sqlUrl=jdbc:postgresql://localhost:5432/ong
sqlUsername=ong
sqlPassword=ong

**Comment by elbywan** [comment]
Avez vous bien fait un `gradle generateConf` ou `gradle generateTestConf`après avoir modifié respectivement `conf.properties` ou `test.properties` ?

**Comment by dgu123** [comment]
Yes

**Comment by elbywan** [comment]
`test.properties` et `conf.properties` ne paramètrent pas directement le springboard.
Les commandes `gradle generateConf` et`gradle generateTestConf` permettent de générer le vrai fichier de paramétrage, qui s'appelle `ent-core.embedded.json`.

**C'est ce fichier qui est pris en compte.**

Trouvez dans ce fichier l'objet correspondant au module `fr.wseduc~mod-postgresql`.
Il est de la forme (la version peut différer) : 

``` json
{
      "name": "fr.wseduc~mod-postgresql~0.2-SNAPSHOT",
      "config": {
        "address" : "sql.persistor",
        "worker" : true,
        "multi-threaded" : true,
        "url" : "jdbc:postgresql://localhost:5432/ong",
        "username" : "web-education",
        "password" : "We_1234"
      }
    }
```

Chez vous, si c'est bien pris en compte et que les bonnes commandes gradle ont été passées, "username" devrait valoir `ong`. 
Or il est vraisemblable qu'il vaille plutôt `web-education`.

Je vous laisse le soin de vérifier votre config.

**Comment by dgu123** [comment]
merci super !!
